### ISSUE TITLE
Unable to start 1.1 on Synology DS1515+ DSM 6

### ISSUE THREAD

**Issue by Wolf666** [ukdtom/WTInstaller#14] opened 2016-04-22 18:40 UTC
I removed old one, installed but it does not start.

**Comment by ChuckPa** [comment] 2016-04-22 19:24
![plex-webtools-dsm-6 0-u3](https://cloud.githubusercontent.com/assets/17990272/14752626/62c20f9c-089e-11e6-8ebf-f2f7c063461f.png)
Because of its dependence on Plex and being unable to stop/start Plex while installing the package, Plex must be manually stopped first.
1. Install the package but do not run (or let it fail which is harmless)
2. Start Plex
   .. wait a second for Plex to get started
3. Start WebTools

It will respond with running as the state after this and you can pull down the launcher shortcut from the menu as always.    

This is a one-time sequence as of DSM 6.0 and the requirement Plex be stopped for the upgrade.

WebTools always requires Plex be stopped when being updated because Plex keeps the connection for WebTools in a 'Listening' state while it is running.

My development system was rebuilt fresh on DSM 6.0 and upgraded to Update 3 all at once and performed this same sequence.  Now, all is as it was with DSM 5.2

**Comment by Wolf666** [comment] 2016-04-22 19:38
ok, I will uninstall and repeat the correct sequence.

**Comment by ukdtom** [comment] 2016-04-22 19:55
Closing this.
Can be reopened if needed

**Comment by Wolf666** [comment] 2016-04-22 23:49
I just stopped Plex, unistalled WebTools, removed any leftover from /volume1/@appstore and /var/packages. 
Reinstalled, restarted Plex, but Webtools failed to start.

**Comment by ChuckPa** [comment] 2016-04-23 01:27
Is this on DSM 5 or DSM 6?

**Comment by Wolf666** [comment] 2016-04-23 08:01
DSM 6 update 3.

**Comment by ChuckPa** [comment] 2016-04-23 15:07
New issue:  DSM 6.0 Update 3:  breaks uninstall in some cases. (cannot uninstall)

Fixes in progress.

**Comment by ibrahimsuzer** [comment] 2016-04-25 07:52
I also have the same problem. I installed this while plex was already running and package failed to start. Stopping plex and trying again also doesn't work. And uninstall doesn't work so I can't try over again.

**Comment by ChuckPa** [comment] 2016-04-25 14:15
Thank you for reporting this.  The issue is known and I have fixed it in v1.2.   Version 1.2 can install even if v1.1 already installed.   V1.2 correctly installs, uninstalls and repairs installations of v1.0 and v1.1

**Comment by Wolf666** [comment] 2016-05-01 09:08
1.3 installed but I had to remove manually previous installation, if not 1.3 was unable to install even with Plex stopped.

**Comment by ChuckPa** [comment] 2016-05-01 15:31
That was a known problem with 1.1 and DSM 5.2 vs DSM 6.    It is why 1.2 was not released.   1.3 is the result of a somewhat painful learning curve for DSM 6 development.

For those who don't want to remove it manually,  I have a utility which will fix WebTools based on whether DSM 5 or 6 so it can be removed / upgraded normally in package center.  

I apologize for the difficulties.   There are still some bugs in DSM 6 which caused issues and I had not fully anticipated.

In the release notes for 1.3, there is mention of one known DSM - browser issue.   It is beyond my control to address.

**Comment by ibrahimsuzer** [comment] 2016-05-01 17:09
Can I get that utility? Or a way to uninstall manually as I don't know how.

I tried 1.3 but it gives "failed to update Webtools" error. And I can't uninstall Webtools as it also gives an error as well.

**Comment by ChuckPa** [comment] 2016-05-01 17:31
If you are comfortable with doing the uninstall using the Synology tools at the command line  (which is what the repair does)

ssh to the box:
sudo -su root  (get to 'root')

/usr/syno/bin/synopkg  uninstall WebTools
/usr/syno/bin/servicetool --remove-configure-file --package WebTools.sc
/usr/syno/bin/servicetool --remove-configure-file --build-in WebTools

If you're not comfortable with this,  Which version of DSM are you using?   DSM 5.2 or 6.0 ?

**Comment by ChuckPa** [comment] 2016-05-01 19:06
https://github.com/ChuckPa/WTrepair

**Comment by ibrahimsuzer** [comment] 2016-05-02 10:02
The utility solved the problem. Thanks a lot.

**Comment by ChuckPa** [comment] 2016-05-02 12:41
You are welcome.  I am glad everything works as it should now.  
Don't you 'love' DSM?  :)

**Closed as completed** 2016-07-19 13:29 UTC
